from pathlib import Path

path = Path('/home/ubuntu/quji-event-service-prototype/client/src/pages/Home.tsx')
s = path.read_text()

old = '''<div className={`p-3 border-t border-slate-200 ${sidebarCollapsed ? 'flex justify-center' : ''}`}><button onClick={() => setSidebarCollapsed(!sidebarCollapsed)} title={sidebarCollapsed ? '展开侧边栏' : '收起侧边栏'} aria-label={sidebarCollapsed ? '展开侧边栏' : '收起侧边栏'} className="mb-2 w-8 h-8 rounded-md border border-slate-200 flex items-center justify-center text-slate-500 hover:text-slate-900 hover:bg-slate-50"><PanelLeftClose className={`w-4 h-4 transition-transform ${sidebarCollapsed ? 'rotate-180' : ''}`} /></button><button onClick={() => setNotificationOpen(true)} title="通知中心" className={`w-full h-10 rounded-lg flex items-center text-[14px] hover:bg-slate-100 ${sidebarCollapsed ? 'justify-center px-2' : 'px-3 gap-3'}`}><Bell className="w-[18px] h-[18px]" />{!sidebarCollapsed && <span>通知中心</span>}{!sidebarCollapsed && <span className="ml-auto w-2 h-2 rounded-full bg-rose-500" />}</button><button onClick={() => setSettingOpen(true)} title="系统设置" className={`w-full h-10 rounded-lg flex items-center text-[14px] hover:bg-slate-100 ${sidebarCollapsed ? 'justify-center px-2' : 'px-3 gap-3'}`}><Settings2 className="w-[18px] h-[18px]" />{!sidebarCollapsed && <span>系统设置</span>}</button><div className={`mt-3 rounded-md bg-slate-50 border border-slate-200 flex items-center ${sidebarCollapsed ? 'p-1.5 justify-center' : 'p-3 gap-2'}`}><div className={`w-8 h-8 rounded-full ${ROLE_INFO[role].color} text-white flex items-center justify-center text-[13px] font-semibold`}>{role === 'organizer' ? '林' : role === 'culture' ? '王' : role === 'collaborator' ? '艾' : '周'}</div>{!sidebarCollapsed && <><div className="min-w-0 flex-1"><div className="text-[13px] font-semibold truncate">{role === 'organizer' ? '林洁' : role === 'culture' ? '王处长' : role === 'collaborator' ? '艾警官' : '周可'}</div><div className="text-[12px] text-slate-500 truncate">{roleLabel}</div></div><button onClick={() => setSignedIn(false)} title={t.logout} className="w-7 h-7 flex items-center justify-center rounded hover:bg-white text-slate-500"><LogOut className="w-4 h-4" /></button></>}</div></div>'''

new = '''<div className={`sidebar-footer shrink-0 border-t border-slate-200 ${sidebarCollapsed ? 'p-2' : 'p-3'}`}><div className={`flex ${sidebarCollapsed ? 'flex-col items-center gap-2' : 'flex-col gap-1'}`}><button onClick={() => setSidebarCollapsed(!sidebarCollapsed)} title={sidebarCollapsed ? '展开侧边栏' : '收起侧边栏'} aria-label={sidebarCollapsed ? '展开侧边栏' : '收起侧边栏'} className={`sidebar-toggle h-8 rounded-md border border-slate-200 flex items-center justify-center text-slate-500 hover:text-slate-900 hover:bg-slate-50 ${sidebarCollapsed ? 'w-8' : 'w-8 mb-1'}`}><PanelLeftClose className={`w-4 h-4 transition-transform ${sidebarCollapsed ? 'rotate-180' : ''}`} /></button><button onClick={() => setNotificationOpen(true)} title="通知中心" aria-label="通知中心" className={`h-9 rounded-md flex items-center text-[14px] hover:bg-slate-100 ${sidebarCollapsed ? 'w-8 justify-center' : 'w-full px-3 gap-3'}`}><span className="relative flex"><Bell className="w-[18px] h-[18px]" />{sidebarCollapsed && <span className="absolute -top-1 -right-1 w-1.5 h-1.5 rounded-full bg-rose-500" />}</span>{!sidebarCollapsed && <span>通知中心</span>}{!sidebarCollapsed && <span className="ml-auto w-2 h-2 rounded-full bg-rose-500" />}</button><button onClick={() => setSettingOpen(true)} title="系统设置" aria-label="系统设置" className={`h-9 rounded-md flex items-center text-[14px] hover:bg-slate-100 ${sidebarCollapsed ? 'w-8 justify-center' : 'w-full px-3 gap-3'}`}><Settings2 className="w-[18px] h-[18px]" />{!sidebarCollapsed && <span>系统设置</span>}</button></div><div className={`sidebar-profile mt-2 ${sidebarCollapsed ? 'flex justify-center' : 'rounded-md bg-slate-50 border border-slate-200 p-3 flex items-center gap-2'}`}><div title={sidebarCollapsed ? roleLabel : undefined} className={`w-8 h-8 rounded-full ${ROLE_INFO[role].color} text-white flex items-center justify-center text-[13px] font-semibold`}>{role === 'organizer' ? '林' : role === 'culture' ? '王' : role === 'collaborator' ? '艾' : '周'}</div>{!sidebarCollapsed && <><div className="min-w-0 flex-1"><div className="text-[13px] font-semibold truncate">{role === 'organizer' ? '林洁' : role === 'culture' ? '王处长' : role === 'collaborator' ? '艾警官' : '周可'}</div><div className="text-[12px] text-slate-500 truncate">{roleLabel}</div></div><button onClick={() => setSignedIn(false)} title={t.logout} aria-label={t.logout} className="w-7 h-7 flex items-center justify-center rounded hover:bg-white text-slate-500"><LogOut className="w-4 h-4" /></button></>}</div></div>'''

if old not in s:
    raise SystemExit('Sidebar footer source was not found')

path.write_text(s.replace(old, new, 1))
print('Rebuilt collapsed sidebar footer as a vertical control rail')
